# Generated by Django 4.2.7 on 2023-11-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('biography', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('icon', models.ImageField(null=True, upload_to='icon/')),
                ('adult_flag', models.BooleanField(default=0)),
                ('ban_count', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('hash_password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='idx_email'), models.Index(fields=['user_name'], name='idx_user_name')],
            },
        ),
    ]
